{{- if and (eq .Values.api.config.storage.backend "filesystem") .Values.storage.filesystem.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "terrapod.fullname" . }}-storage
  labels:
    {{- include "terrapod.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    {{- toYaml .Values.storage.filesystem.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.filesystem.persistence.size }}
  {{- if .Values.storage.filesystem.persistence.storageClass }}
  storageClassName: {{ .Values.storage.filesystem.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
